- name: setup gitconfig
  copy:
    content: |
      [user]
        name = {{ git_user }}
        email = {{ git_email }}

      [push]
        default = simple

      [core]
        editor = {{ git_editor }}

    dest: ~/.gitconfig
    mode: '0644'

- name: Create an ssh key, if it doesn't exist already
  command: ssh-keygen -b 4096 -f ~/.ssh/id_rsa -q -t rsa -C "{{ ansible_user_id }}@{{ ansible_ssh_host }}" -N ""
  args:
    creates: ~/.ssh/id_rsa
