- name: synchronize vim configs
  synchronize:
    src: ../files/
    dest: ~/
    archive: yes
    perms: no

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    clone: yes
    update: yes

- name: install nvim plugins
  command: nvim +PluginClean! +PluginInstall +UpdateRemotePlugins +PluginUpdate +qall
  when: install_neovim

