- name: install software
  homebrew:
    name:
      - ag
      - bat
      - jq
      - gradle
      - golang
      - neovim
      - python3
      - wget
      - rsync
      - tmux
      - tree
      - zsh
    state: latest
    update_homebrew: yes
    upgrade_all: yes

- name: set zsh executable fact
  set_fact:
    zsh_executable: /usr/local/bin/zsh

- name: symlink vim to nvim
  file:
    state: link
    src: /usr/local/bin/nvim
    dest: /usr/local/bin/vim

